### ISSUE TITLE
首页读取异常

### ISSUE THREAD

**Issue by CCXXXI** [re0wiki/wiki-bot#333]
这几乎总是导致脚本提前结束：

<details><summary>Details</summary>
<p>

```
(re0wiki) PS C:\Users\ccxxx\Documents\GitHub\wiki-bot> python "pywikibot/pwb.py" "fixing_redirects" "-page:Sandbox"
Retrieving 1 pages from re0:zh.


>>> Sandbox <<<

1 read operation
Execution time: 1 seconds
Read operation time: 1.0 seconds
Script terminated by exception:

ERROR: APISite instance has no attribute 'userinfo' (AttributeError)
Traceback (most recent call last):
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pwb.py", line 40, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pwb.py", line 36, in main
    runpy.run_path(str(path), run_name='__main__')
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\scripts\wrapper.py", line 521, in <module>
    main()
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\scripts\wrapper.py", line 505, in main
    if not execute():
           ^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\scripts\wrapper.py", line 492, in execute
    run_python_file(filename, script_args, module)
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\scripts\wrapper.py", line 149, in run_python_file
    exec(compile(source, filename, 'exec', dont_inherit=True),
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\scripts\fixing_redirects.py", line 267, in <module>
    main()
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\scripts\fixing_redirects.py", line 261, in main
    bot.run()
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\bot.py", line 1489, in run
    self.treat(page)
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\bot.py", line 1742, in treat
    self.treat_page()
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\scripts\fixing_redirects.py", line 208, in treat_page
    newtext = self.replace_links(newtext, page, target)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\scripts\fixing_redirects.py", line 90, in replace_links
    is_interwikilink = mysite.isInterwikiLink(m['title'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_basesite.py", line 367, in isInterwikiLink
    linkfam, linkcode = pywikibot.Link(text, self).parse_site()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\page\_links.py", line 365, in parse_site
    newsite = self._source.interwiki(prefix)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_apisite.py", line 163, in interwiki
    return self._interwikimap[prefix].site
           ~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_interwikimap.py", line 79, in __getitem__
    raise self._iw_sites[prefix].site
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_interwikimap.py", line 26, in site
    self._site = pywikibot.Site(
                 ^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\__init__.py", line 194, in Site
    code, fam = _code_fam_from_url(url, fam)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\__init__.py", line 105, in _code_fam_from_url
    code = family.from_url(url)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\family.py", line 637, in from_url
    site = pywikibot.Site(code, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\__init__.py", line 243, in Site
    _sites[key] = interface(code=code, fam=fam, user=user)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_apisite.py", line 140, in __init__
    self.login(cookie_only=True)
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_apisite.py", line 400, in login
    if self.userinfo['name'] == self.user():
       ^^^^^^^^^^^^^
  File "C:\Users\ccxxx\Documents\GitHub\wiki-bot\pywikibot\pywikibot\site\_basesite.py", line 217, in __getattr__
    raise AttributeError(f'{type(self).__name__} instance has no '
AttributeError: APISite instance has no attribute 'userinfo'
CRITICAL: Exiting due to uncaught exception AttributeError: APISite instance has no attribute 'userinfo'

``` 

</p>
</details>

**Comment by CCXXXI** [comment]
经过测试，当以下内容出现在同一个条目时会出问题：

- 一个重定向链接
- 一个 `w:c:` 链接

例如：
```wikitext
[[艾米莉娅]]
[[w:c:zh.ngnl]]
```

**Comment by CCXXXI** [comment]
在代码上看不出原因，修不了。

但是可以 [手动避免 `w:c:` 链接](https://rezero.fandom.com/zh/wiki/Re:%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E7%9A%84%E5%BC%82%E4%B8%96%E7%95%8C%E7%94%9F%E6%B4%BB_Wiki?diff=205126&oldid=205012)。

**Comment by CCXXXI** [comment]
猜想：bot 把 `[[]]` 格式的链接当成了内部链接，然后追着这个链接去了 ngnl 站，发现在那里无法登录？
